version: "3.7"

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  rocky:
    depends_on:
      - db
    build: .
    image: wordpress-on-rocky
    container_name: wordpress-on-rocky
    privileged: true
    restart: always
    ports:
      - "44080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./conf_files/www.conf:/etc/php-fpm.d/www.conf
      - ./conf_files/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./conf_files/php.ini:/etc/php.ini
      - ./html:/var/www/html
      - type: bind
        source: ./log/httpd
        target: /var/log/httpd
      - type: bind
        source: ./share
        target: /share

  mailhog:
    image: jcalonso/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data: